# Generated by Django 4.2.4 on 2023-09-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='field_of_stay',
            new_name='field_of_study',
        ),
    ]
